// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuUKanY-ajnNKV0WPTxSnC9v8kqgudDTY',
    appId: '1:467431245181:web:61faecb178cb80a25eb814',
    messagingSenderId: '467431245181',
    projectId: 'flutter-apple-45a51',
    authDomain: 'flutter-apple-45a51.firebaseapp.com',
    storageBucket: 'flutter-apple-45a51.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKyuVPUaIXtDv1bqi6CYc4Ze5SH8Kzs7g',
    appId: '1:467431245181:android:a02085008f8e19fb5eb814',
    messagingSenderId: '467431245181',
    projectId: 'flutter-apple-45a51',
    storageBucket: 'flutter-apple-45a51.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyjeZ3i5T7XDV0ShXDMsICVsiAfDwc7AI',
    appId: '1:467431245181:ios:2e5740239ed4c2c25eb814',
    messagingSenderId: '467431245181',
    projectId: 'flutter-apple-45a51',
    storageBucket: 'flutter-apple-45a51.appspot.com',
    iosClientId: '467431245181-ftpb16dcvt747m5t00gs9shug0c5q9nq.apps.googleusercontent.com',
    iosBundleId: 'com.hanseijaehee.instagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyjeZ3i5T7XDV0ShXDMsICVsiAfDwc7AI',
    appId: '1:467431245181:ios:2e5740239ed4c2c25eb814',
    messagingSenderId: '467431245181',
    projectId: 'flutter-apple-45a51',
    storageBucket: 'flutter-apple-45a51.appspot.com',
    iosClientId: '467431245181-ftpb16dcvt747m5t00gs9shug0c5q9nq.apps.googleusercontent.com',
    iosBundleId: 'com.hanseijaehee.instagram',
  );
}
