// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1sls2DEZeN-uMdLR957HeuQFXdNFNDKs',
    appId: '1:1041520466255:web:9180ddf2b629898ae38d3a',
    messagingSenderId: '1041520466255',
    projectId: 'fluttergram-2a2a4',
    authDomain: 'fluttergram-2a2a4.firebaseapp.com',
    storageBucket: 'fluttergram-2a2a4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA43DZ5PKXB4hdgyjn0hWZXBAmmzU-e3UU',
    appId: '1:1041520466255:android:55accb82ec287dc6e38d3a',
    messagingSenderId: '1041520466255',
    projectId: 'fluttergram-2a2a4',
    storageBucket: 'fluttergram-2a2a4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9cuuoalAwhxCd8OmOA3Mx303X4wX9gxI',
    appId: '1:1041520466255:ios:73606e6c44c3185be38d3a',
    messagingSenderId: '1041520466255',
    projectId: 'fluttergram-2a2a4',
    storageBucket: 'fluttergram-2a2a4.appspot.com',
    iosClientId: '1041520466255-tgdu5ih149kr692pheehical547s9t3g.apps.googleusercontent.com',
    iosBundleId: 'com.hanseijaehee.instagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9cuuoalAwhxCd8OmOA3Mx303X4wX9gxI',
    appId: '1:1041520466255:ios:73606e6c44c3185be38d3a',
    messagingSenderId: '1041520466255',
    projectId: 'fluttergram-2a2a4',
    storageBucket: 'fluttergram-2a2a4.appspot.com',
    iosClientId: '1041520466255-tgdu5ih149kr692pheehical547s9t3g.apps.googleusercontent.com',
    iosBundleId: 'com.hanseijaehee.instagram',
  );
}
